services:
  app:
    build:
      context: /share/Container/BGPostNoticeGenerationUpload
      dockerfile: Dockerfile  
    container_name: BgPostNoticeGeneration_Container
    ports:
      - "5341:5341"          
    environment:
      PORT: "5341"
      OFFICE_IPS: '{"841": ["192.168.100.201", "192.168.100.182", "192.168.100.213", "172.20.10.4"], "910": ["192.168.65.1"], "870": ["95.43.125.221"]}'
      TRUST_PROXY: "true"
    volumes:
      - /share/Container/BGPostNoticeGenerationUpload/backend/config:/app/config